### Send valid Zipcode POST request with json body
GET http://localhost:8181
Content-Type: application/json

{
  "zipcode": "22224444"
}

### Send invalid Zipcode POST request with json body
GET http://localhost:8181
Content-Type: application/json

{
  "zipcode": "999999"
}
