services:

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    depends_on:
      - otel-collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver

  app1:
    container_name: app1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: app1
    environment:
      -
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - prometheus
      - otel-collector

  app2:
    container_name: app2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: app2
    environment:
      -
    ports:
      - "8181:8181"
    depends_on:
      - zipkin
      - prometheus
      - otel-collector